### Get all users
GET http://localhost:4000/users
Content-Type: application/json

### Register new user
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Joe", "password": "secret"
}

### Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Joe",
    "password": "secret"
}

### Login failure
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "Joe", "password": "fail"
}