### Get all users
GET http://localhost:4000/users HTTP/1.1
Content-Type: application/json

### Register new user
POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "secret"
}

### Login
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "secret"
}

### Login failure
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "fail"
}

### Protected route
GET http://localhost:4000/protected-ping HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkpvZSIsImlhdCI6MTU5MDM3MTQwNSwiZXhwIjoxNTkwMzcyMDA1fQ.2BjJXQ18yHUceLavQXgHA8RlxaJmM67WyCzsIssTZHI

### Protected route failure
GET http://localhost:4000/protected-ping HTTP/1.1
Content-Type: application/json
Authorization: invalidAuthorizationToken