### Get all users
GET http://localhost:4000/users HTTP/1.1
Content-Type: application/json

### Register new user
POST http://localhost:4000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "secret"
}

### Login
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "secret"
}

### Login failure
POST http://localhost:4000/login HTTP/1.1
Content-Type: application/json

{
    "name": "Joe", "password": "fail"
}

### Protected route
GET http://localhost:4000/protected-ping HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJKb2UifSwiaWF0IjoxNTkwNTExMTU3LCJleHAiOjE1OTA1MTE3NTd9.Ihu6EFduhoYQfjUKkmQlcrMEYiT-Y6_E46nFAkiAJPo

### Protected route failure
GET http://localhost:4000/protected-ping HTTP/1.1
Content-Type: application/json
Authorization: invalidAuthorizationToken

### Refreh token from cookie
GET http://localhost:4000/refresh-login HTTP/1.1
Content-Type: application/json

### Logout
POST http://localhost:4000/logout HTTP/1.1
Content-Type: application/json